stages:
  - install_dependencies
  - build
  - deploy

before_script:
  - export APP_CONTAINER_NAME=accounting-front-container

install_dependencies accounting:
  stage: install_dependencies
  image: node:11-alpine
  tags:
    - accounting
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - yarn install
  only:
    refs:
      - master
      - tags
    changes:
      - package-lock.json

build accounting:
  stage: build
  image: node:11-alpine
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - dist
  tags:
    - accounting
  variables:
    api: localhost/api
  script:
    - docker build -t "accounting:${CI_COMMIT_SHORT_SHA}" .
  only:
    - master
    - tags


deploy accounting:
  stage: deploy
  tags:
    - accounting
  script:
    - docker stop "$APP_CONTAINER_NAME" || true
    - docker run --name "$APP_CONTAINER_NAME" -p 80:80 -d "accounting:${CI_COMMIT_SHORT_SHA}"
    - docker system prune -af
  only:
    - master
    - tags
