version: '3.4'

services:

  aurelia_front:
    container_name: aurelia_front
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "4567:4567"
      - "6060:6060"
