name: build

on:
  push:
    branches:
      - manufacturing-warehouse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: '13.10'
      - name: Install npm
        run: |
          npm install
        env:
          CI: true
      - name: Publish to Dockerhub Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: timoloomets/manufacturing
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: latest
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: DOCKER_USERNAME, DOCKER_PASSWORD
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rm -vf $(sudo docker ps -aq)
            sudo docker rmi -f $(sudo docker images -aq)
            sudo docker volume prune -f
            sudo docker image ls
            sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            sudo docker run -dit -p 80:80 timoloomets/manufacturing:latest
