name: build

on:
  push:
    branches:
      - manufacturing-warehouse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: '13.10'
      - name: Install npm
        run: |
          npm install
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tutinformatics/accounting_ui/accounting_ui
          registry: docker.pkg.github.com
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.DROPLET_PORT }}
          envs: DEPLOY_USERNAME, GITHUB_TOKEN
          script: |
            whoami
            echo $DEPLOY_USERNAME
            echo $GITHUB_TOKEN
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker login docker.pkg.github.com -u TimoLoomets -p $GITHUB_TOKEN
            sudo docker run -dit -p 80:80 docker.pkg.github.com/tutinformatics/accounting_ui/accounting_ui:latest
