name: build

on:
  push:
    branches:
      - manufacturing-warehouse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: '13.10'
      - name: Install npm
        run: |
          npm install
        env:
          CI: true
      - name: Print environment variables
          run: |
            echo $username
            echo $password
          env:
            username: ${{ secrets.GITHUB_USERNAME }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: TimoLoomets/accounting-ui/manufacturing-warehouse-ui
          registry: docker.pkg.github.com
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
